travis:
  secure:
    BINSTAR_TOKEN: eGQM/VgzhhwgMOZ5RyTBBMZta5+G3paKe3InNpRRh9MAu4i8nV/9A+GlesaDYKc7fGceqqcnR9AT9bpHyrg6j0nRljaHeUf4D27xtbnm+G1M0II/NL+dHYACBBn2u/rKln13buCfZWF/6KCI12ITTZmerLFQJ1C3yYlM6vLTCy68HD8UG55Mz7qLto+k1/yGqOOOG4DN+OM7WF/PhgdFBXj0obdnoJecw2scIUSXpBJ6nszb6szNU/vnlz5tl4Y/7sGouRCU91MIbh8mhQH4zfHqvFAmIwx3/WvqHHQOkdWFLbjNnYOz6zYrZoi1GXYUjWZO0PZNWOZZjOgaKNB89goEloVPG9Qs7Vg6BcRb0wsTGfhSJj9dNjcSrI9JZce+I5P98E35RxbnWeHTCp7fcRckSRxogBgLDonxSNbXFwg0iMj8X8ULtQ/sU3fngp8CJl6VWbmsxcF3SqNWnRvfbc3l0aDxBZDrgQuqcrMWI2bH/o/pvJpsmb0hBo5DmBumG1P7Zp9BluWOSgQLf651RjePBWYScb0eb/vu19Rzc19++R/BluOeS4v0Pfk07FgOFELtAgBJPDAC1G0KjqxSKWbsPgiEWt0M2kJ7tPt5c6MyeCAGHNCrNFoJ5kjl7t1XaYIuVqKUV4tzPYrf8LgDtjawLUGjY+GovD9Z94pd7UU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
